#!/bin/bash

if [ "$1" = "" ]; then
  echo "Problem name is empty"
  exit 1
fi

probname=$1

sdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
pdir=$PWD

temppath="${sdir}/template-solver.cpp"

pfilepath="${pdir}/${probname}.cpp"
ifilepath="${pdir}/${probname}.in"
ofilepath="${pdir}/${probname}.out"

`cp -n ${temppath} ${pfilepath}`
touch "${ifilepath}"
touch "${ofilepath}"

sed -i '' -e "s/{\$__PROB__}/${probname}/g" ${pfilepath}
curdate=`date +%-m/%-d/%Y`
curtime=`date +%-H:%M`
sed -i '' -e "s|{\$__DATE__}|${curdate}|g" ${pfilepath}
sed -i '' -e "s|{\$__TIME__}|${curtime}|g" ${pfilepath}

command="g++ -std=c++14 -Wall -O2 -D_GLIBCXX_DEBUG -fsanitize=address ${probname}.cpp && ./a.out"
echo $command

open "${pfilepath}"
open "${ifilepath}"
open "${ofilepath}"
